version: '3'

services:
  website:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysqldb
    volumes:
      - game_files:/game_files
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=wabs
  adminer:
    image: adminer
    restart: always
    ports:
      - '8085:8080'

volumes:
  mysql_data:
  game_files: